"""Correction API — Retrieves the latest expression correction for a session.

GET /correction/{session_id}  →  Latest correction JSON
"""

from fastapi import APIRouter, HTTPException

from agents.correction_store import CorrectionStore

router = APIRouter()


@router.get("/{session_id}")
async def get_correction(session_id: str):
    """Get the latest real-time expression correction for a session.

    Returns the correction generated by CorrectionAgent during the
    most recent message exchange. Returns 404 if no correction exists.

    Response shape:
    {
      "has_correction": true | false,
      "original": "<problematic phrase>",       // if has_correction
      "corrected": "<improved version>",        // if has_correction
      "explanation": "<brief explanation>",     // if has_correction
      "type": "grammar|vocabulary|style|fluency", // if has_correction
      "tts_text": "Try saying it like this..." // if has_correction
    }
    """
    store = CorrectionStore.get_instance()
    correction = store.get(session_id)

    if correction is None:
        raise HTTPException(status_code=404, detail="No correction found for this session")

    return correction
